# Generated by Django 5.2 on 2025-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonowiseapp', '0003_progressousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressousuario',
            name='acertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressousuario',
            name='erros',
            field=models.IntegerField(default=0),
        ),
    ]
